version: "3.5"
services: 
  recommender:
    image: procare_re:1.0
    restart: always
    networks:
        - data_net
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    networks:
        - data_net
    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=procare
      - POSTGRES_DB=procare
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  postgres_data:

networks:
  data_net:
    driver: overlay
