version: "3.5"
volumes:
  dbpostgresql-rec:
    external: false

networks:
  data-repo-net:
    external: false
    name: data-repo-net

services:
  recommender:
    container_name: "recommender-procare"
    image: kaiser1414/procare-recommender:latest
    restart: always
    networks:
        - data-repo-net
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - db
  db:
    container_name: "dbpostgresql-rec"
    image: postgres
    restart: always
    networks:
        - data-repo-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=procare
      - POSTGRES_DB=procare
    volumes:
      - dbpostgresql-rec:/var/lib/postgresql/data
    ports:
      - "5432:5432"
