version: "1.0"
services: 
  recommender:
    image: procare_re:1.0
    restart: always
    networks:
      data_net:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - db
    environment:
      - TESTING=yes
    deploy:
      placement:
        constraints: [
          node.role == manager
        ]
  db:
    image: postgres
    restart: always
    networks:
      data_net:
#    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=tender
#      - POSTGRES_DB=procare
    volumes:
      - postgress_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [
          node.role == manager
        ]

volumes:
  postgress_data:

networks:
  data_net:
    external: true
